### ISSUE TITLE
Backend Exception should set authenticated and connected properties to False

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-backend-client#29]
When Backend Exception is raise (when Backend is not available),  `authenticated` (and `connected`) properties are not reset.

```python
from alignak_backend_client.client import Backend
backend = Backend('http://192.168.195.131:5000')
backend.login('admin', 'admin')
>>> True
backend.authenticated
>>> True
# Shut down backend
... 
backend.authenticated
>>> True
backend.login('admin', 'admin')
ERROR:alignak_backend_client.client:Backend connection error, error: HTTPConnectionPool(host='192.168.195.131', port=5000): Max retries exceeded with url: /login (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fc4c485c750>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mea/.local/lib/python2.7/site-packages/alignak_backend_client/client.py", line 176, in login
    raise BackendException(1000, "Backend connection error")
alignak_backend_client.client.BackendException: Backend error code 1000: Backend connection error
```

I'm also not sure `connected` property is set somewhere... it is always `False` !

**Comment by mohierf** [comment]
**Confirmed**: `connected`property is always False!

The `authenticated` property is set/unset according to the login / logout functions to confirm that the current credentials are accepted.

The `connected` property will be removed because it makes no sense.

**Comment by algorys** [comment]
`connected` property have been removed.

But `authenticated` stays true no matter what happens (if not internet connection, backend available).

It would be nice if client had a system to check if backend still available or not. Maybe with a periodical refresh or before any requests (GET / POST / PATCH). 

Like that user of client can test before if `authenticated` is `True` or `False`.

@ddurieux and @mohierf , Do you think this is possible?
