### ISSUE TITLE
Default realm creation error

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-backend-client#36]
When creating a default realm, an error is raised because of an unknown `_realm` field:
```
alignak-backend-cli -t realm add test
INFO:alignak_backend_client.client:Authenticating...
INFO:alignak_backend_client.client:Authenticated.
INFO:alignak_backend_client.client:Found realm 'All': 5912ed4606fd4b0e20c61839
INFO:alignak_backend_client.client:Found logged-in user realm: All
INFO:alignak_backend_client.client:Found TP '24x7': 5912ed4606fd4b0e20c6183d
INFO:alignak_backend_client.client:Found TP 'Never': 5912ed4606fd4b0e20c6183e
INFO:alignak_backend_client.client:Got 1 realms
INFO:alignak_backend_client.client:-> json item: {'name': 'test'}
INFO:alignak_backend_client.client:Trying to get realm: 'test'
INFO:alignak_backend_client.client:add default realm to the data
INFO:alignak_backend_client.client:-> trying to create the realm: test.
ERROR:alignak_backend_client.client:backend error: 422, Insertion failure: 1 document(s) contain(s) error(s)
ERROR:alignak_backend_client.client: - issue: _realm: unknown field
ERROR:alignak_backend_client.client:Exception: Backend error code 422: Insertion failure: 1 document(s) contain(s) error(s)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak_backend_client-0.9.0-py2.7.egg/alignak_backend_client/backend_client.py", line 973, in create_update_resource
    response = self.backend.post(resource_name, item_data, headers=None)
  File "/usr/local/lib/python2.7/dist-packages/alignak_backend_client-0.9.0-py2.7.egg/alignak_backend_client/client.py", line 548, in post
    raise BackendException(error['code'], error['message'], resp)
BackendException: Backend error code 422: Insertion failure: 1 document(s) contain(s) error(s)
ERROR:alignak_backend_client.client:Response: {u'_status': u'ERR', u'_issues': {u'_realm': u'unknown field'}, u'_error': {u'message': u'Insertion failure: 1 document(s) contain(s) error(s)', u'code': 422}}
Creation/update error for  'realm' : test
~~~~~~~~~~~~~~~~~~~~~~~~~~
Exiting with error code: 5
ERROR:alignak_backend_client.client:realm 'test' add failed
WARNING:alignak_backend_client.client:Set verbose mode to have more information (-v)

```

**Comment by mohierf** [comment]
This error occur because the `realm` backend endpoint do not have a `_realm` field but a `_parent` field ... the `alignak-backend-cli` should not set the default realm when a new realm is created.
