### ISSUE TITLE
login with "="  in "[-b=url] [-u=username] [-p=password]" does not work

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-backend-client#43]
````
alignak-backend-cli command line interface::

    Usage:
        alignak-backend-cli [-h]
        alignak-backend-cli [-V]
        alignak-backend-cli [-v] [-q] [-c] [-l] [-m] [-e] [-i]
                            [-b=url] [-u=username] [-p=password]
````

**With "=" does not work**
````
alignak-backend-cli -b=http://127.0.0.1:5000 -u=admin -p=admin get -l -v

DEBUG:alignak_backend_client.client:Dry-run mode (check only): False
DEBUG:alignak_backend_client.client:Backend URL: =http://127.0.0.1:5000
DEBUG:alignak_backend_client.client:Backend login with credentials: =admin/=admin
DEBUG:alignak_backend_client.client:Get a list: True
DEBUG:alignak_backend_client.client:Get the templates: False
DEBUG:alignak_backend_client.client:Item type: host
DEBUG:alignak_backend_client.client:Action to execute: get
DEBUG:alignak_backend_client.client:Targeted item name: None
DEBUG:alignak_backend_client.client:Using the template(s): None
DEBUG:alignak_backend_client.client:Embedded mode: False
DEBUG:alignak_backend_client.client:Data files folder: None
DEBUG:alignak_backend_client.client:Item data provided: None
DEBUG:alignak_backend_client.client:Use backend read data: False
INFO:alignak_backend_client.client:Authenticating...
DEBUG:alignak_backend_client.client:request backend authentication for: =admin, generate: enabled
ERROR:alignak_backend_client.client:Backend connection exception, error: <class 'requests.exceptions.InvalidSchema'> / No connection adapters were found for '=http://login'
ERROR:alignak_backend_client.client:Exception: Backend error code 1000: Backend is not available, response: None
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak_backend_client/backend_client.py", line 398, in initialize
    self.backend.login(self.username, self.password)
  File "/usr/local/lib/python2.7/dist-packages/alignak_backend_client/client.py", line 179, in login
    raise BackendException(1000, "Backend is not available")
BackendException: Backend error code 1000: Backend is not available, response: None
ERROR:alignak_backend_client.client:Response: None
Access denied!
~~~~~~~~~~~~~~~~~~~~~~~~~~
Exiting with error code: 1
````

**With "=" is working**
````
alignak-backend-cli -b http://127.0.0.1:5000 --username=admin --password=admin get localhost
````
**Without "=" is working**
````
alignak-backend-cli -b http://127.0.0.1:5000 --username admin --password admin get localhost

````
````
 alignak-backend-cli -b http://127.0.0.1:5000 -u admin -p admin get localhost
INFO:alignak_backend_client.client:Authenticating...
INFO:alignak_backend_client.client:Authenticated.
INFO:alignak_backend_client.client:Found realm 'All': 59331807a9fb6e02ea91662e
INFO:alignak_backend_client.client:Found logged-in user realm: All
INFO:alignak_backend_client.client:Found TP '24x7': 59331808a9fb6e02ea916632
INFO:alignak_backend_client.client:Found TP 'Never': 59331808a9fb6e02ea916633
INFO:alignak_backend_client.client:Trying to get host: 'localhost'
INFO:alignak_backend_client.client:-> found host 'localhost': 5942bf3ca9fb6e5e67aec79b
INFO:alignak_backend_client.client:-> dumping host: localhost
...
````

**Comment by mohierf** [comment]
Sorry, my bad 😞 

The syntax example is not correct !

**Comment by spea1** [comment]
last help 🔢 

**at the bottom**

````
alignak-backend-cli -h
alignak-backend-cli command line interface::

    Usage:
        alignak-backend-cli [-h]
        alignak-backend-cli [-V]
        alignak-backend-cli [-v] [-q] [-c] [-l] [-m] [-e] [-i]
                            [-b url] [-u username] [-p password]
                            [-d data]
                            [-f folder]
                            [-T template] [-t type] [<action>] [<item>]

    Options:
        -h, --help                  Show this screen.
        -V, --version               Show application version.
        -v, --verbose               Run in verbose mode (more info to display)
        -q, --quiet                 Run in quiet mode (display nothing)
        -c, --check                 Check only (dry run), do not change the backend.
        -l, --list                  Get an items list
        -b, --backend url           Specify backend URL [default: http://127.0.0.1:5000]
        -u, --username=username     Backend login username [default: admin]
        -p, --password=password     Backend login password [default: admin]
        -d, --data=data             Data for the new item to create [default: none]
        -f, --folder=folder         Folder where to read/write data files [default: none]
        -i, --include-read-data     Do not use only the provided data, but append the one
                                    read from he backend
        -t, --type=host             Type of the provided item [default: host]
        -e, --embedded              Do not embed linked objects
        -m, --model                 Get only the templates
        -T, --template=template     Template to use for the new item

    Exit code:
        0 if required operation succeeded
        1 if backend access is denied (check provided username/password)
        2 if element operation failed (missing template,...)

        64 if command line parameters are not used correctly

    Use cases:
        Display help message:
            alignak-backend-cli (-h | --help)

        Display current version:
            alignak-backend-cli -V
            alignak-backend-cli --version

        Specify backend parameters if they are different from the default
            alignak-backend-cli -b=http://127.0.0.1:5000 -u=admin -p=admin get host_name

````
