### ISSUE TITLE
"servicegroups &  usergroups" items list not work

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-backend-client#46]
```
root@nuc:/tmp# alignak-backend-cli get -v -l -f /tmp -t servicegroups
DEBUG:alignak_backend_client.client:Dry-run mode (check only): False
DEBUG:alignak_backend_client.client:Backend URL: http://127.0.0.1:5000
DEBUG:alignak_backend_client.client:Backend login with credentials: admin/admin
DEBUG:alignak_backend_client.client:Get a list: True
DEBUG:alignak_backend_client.client:Get the templates: False
DEBUG:alignak_backend_client.client:Item type: servicegroups
DEBUG:alignak_backend_client.client:Action to execute: get
DEBUG:alignak_backend_client.client:Targeted item name: None
DEBUG:alignak_backend_client.client:Using the template(s): None
DEBUG:alignak_backend_client.client:Embedded mode: False
DEBUG:alignak_backend_client.client:Data files folder: /tmp
DEBUG:alignak_backend_client.client:Item data provided: None
DEBUG:alignak_backend_client.client:Use backend read data: False
INFO:alignak_backend_client.client:Authenticating...
DEBUG:alignak_backend_client.client:request backend authentication for: admin, generate: enabled
DEBUG:alignak_backend_client.client:authentication response: {u'token': u'1504026845698-8996a29d-69bb-4b8f-a361-fb2b6b83f5ab'}
DEBUG:alignak_backend_client.client:user authenticated: admin
INFO:alignak_backend_client.client:Authenticated.
DEBUG:alignak_backend_client.client:get_all, endpoint: user, parameters: {'where': '{"name": "admin"}'}
DEBUG:alignak_backend_client.client:get, endpoint: http://127.0.0.1:5000/user, parameters: {'max_results': 50, 'where': '{"name": "admin"}'}
DEBUG:alignak_backend_client.client:get, response: <Response [200]>
DEBUG:alignak_backend_client.client:get_all, endpoint: realm, parameters: None
DEBUG:alignak_backend_client.client:get, endpoint: http://127.0.0.1:5000/realm, parameters: {'max_results': 50}
DEBUG:alignak_backend_client.client:get, response: <Response [200]>
INFO:alignak_backend_client.client:Found realm 'All': 59a5a0dda9fb6e7771392b32
INFO:alignak_backend_client.client:Found logged-in user realm: All
DEBUG:alignak_backend_client.client:get_all, endpoint: timeperiod, parameters: None
DEBUG:alignak_backend_client.client:get, endpoint: http://127.0.0.1:5000/timeperiod, parameters: {'max_results': 50}
DEBUG:alignak_backend_client.client:get, response: <Response [200]>
INFO:alignak_backend_client.client:Found TP '24x7': 59a5a0dda9fb6e7771392b36
INFO:alignak_backend_client.client:Found TP 'Never': 59a5a0dda9fb6e7771392b37
DEBUG:alignak_backend_client.client:backend_client, version: 0.9.3
DEBUG:alignak_backend_client.client:~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO:alignak_backend_client.client:Trying to get servicegroups list
DEBUG:alignak_backend_client.client:get_all, endpoint: servicegroups, parameters: {}
DEBUG:alignak_backend_client.client:get, endpoint: http://127.0.0.1:5000/servicegroups, parameters: {'max_results': 50}
DEBUG:alignak_backend_client.client:get, response: <Response [404]>
ERROR:alignak_backend_client.client:Exception: Backend error code 404: Not found, response: None
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak_backend_client/backend_client.py", line 490, in get_resource_list
    rsp = self.backend.get_all(resource_name, params=params)
  File "/usr/local/lib/python2.7/dist-packages/alignak_backend_client/client.py", line 402, in get_all
    resp = self.get(endpoint, params)
  File "/usr/local/lib/python2.7/dist-packages/alignak_backend_client/client.py", line 337, in get
    raise BackendException(404, 'Not found')
BackendException: Backend error code 404: Not found, response: None
ERROR:alignak_backend_client.client:Response: None
Get error for 'servicegroups' list
~~~~~~~~~~~~~~~~~~~~~~~~~~
Exiting with error code: 5
ERROR:alignak_backend_client.client:servicegroups 'None' get failed
```

**Comment by mohierf** [comment]
This is because your must use: `alignak-backend-cli get -v -l -f /tmp -t servicegroup`

**Note** that it is `servicegroup` and not `servicegroups` ... you must use the singular form for the backend endpoints :wink:
