### ISSUE TITLE
Using several client processes raises an exception

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-backend-client#67]
When the client library is configured to use more than one process:

```
Process Process-26:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client-1.2.1-py2.7.egg/alignak_backend_client/client.py", line 450, in get_pages
    resp = self.get(endpoint, params)
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client-1.2.1-py2.7.egg/alignak_backend_client/client.py", line 372, in get
    resp = self.decode(response=response)
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client-1.2.1-py2.7.egg/alignak_backend_client/client.py", line 206, in decode
    resp_json = response.json()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 884, in json
    self.content.decode(encoding), **kwargs
  File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting ':' delimiter: line 1 column 7748 (char 7747)

```

**Comment by mohierf** [comment]
This a bad interpretation ... I close!

**Comment by mohierf** [comment]
I re-open because of:
```
[2018-02-28 07:26:15] INFO: [arbiter-master.alignak.module.backend_arbiter] Loading Alignak monitored system configuration...
[2018-02-28 07:26:15] INFO: [arbiter-master.alignak.module.backend_arbiter] Got 2 realms
[2018-02-28 07:26:15] INFO: [arbiter-master.alignak.module.backend_arbiter] Got 4 commands
[2018-02-28 07:26:15] INFO: [arbiter-master.alignak.module.backend_arbiter] Got 3 timeperiods
[2018-02-28 07:26:16] INFO: [arbiter-master.alignak.module.backend_arbiter] Got 4 contacts
[2018-02-28 07:26:16] INFO: [arbiter-master.alignak.module.backend_arbiter] Got 2 contactgroups
[2018-02-28 07:26:22] INFO: [arbiter-master.alignak.module.backend_arbiter] Got 969 hosts
[2018-02-28 07:26:23] INFO: [arbiter-master.alignak.module.backend_arbiter] Got 2 hostgroups
Process Process-16:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client-1.2.1-py2.7.egg/alignak_backend_client/client.py", line 450, in get_pages
    resp = self.get(endpoint, params)
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client-1.2.1-py2.7.egg/alignak_backend_client/client.py", line 372, in get
    resp = self.decode(response=response)
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client-1.2.1-py2.7.egg/alignak_backend_client/client.py", line 206, in decode
    resp_json = response.json()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 884, in json
    self.content.decode(encoding), **kwargs
  File "/usr/local/lib/python2.7/site-packages/simplejson-3.13.2-py2.7-freebsd-11.1-RELEASE-p1-amd64.egg/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/site-packages/simplejson-3.13.2-py2.7-freebsd-11.1-RELEASE-p1-amd64.egg/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/site-packages/simplejson-3.13.2-py2.7-freebsd-11.1-RELEASE-p1-amd64.egg/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting ',' delimiter or '}': line 1 column 7722 (char 7721)

```
